# Site settings
title: DeepSight
email: team.deepsight@gmail.com
description: > # Writer Theme is a responsive template
 focussed on typography, minimal design and
  quality photography built using the Jekyll platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://team-deepsight.github.io" # the base hostname & protocol for your site
enable_retina: true
permalink: :title
nav_list:
  Home : ['home', '/', 'fa-home']
  About : ['about', '/about', 'fa-group']
  Project : ['project', '/project', 'fa-dashboard']
  Contact : ['contact', '/contact', 'fa-plane']
  Github : ['github', 'http://www.naver.com', 'fa-github']
  # Author : ['Author', '/author/michelle', 'fa-user']
single_footer: '<p>"A breakthrough in machine learning" DeepSight &copy; 2016</p>'
footer_links:
    About: ['About', '/about']
    Writer: ['DeepSight 2016', '/about']


# Build settings
# markdown: kramdown 
# <a href="/">latest posts</a>
